apiVersion: apps/v1
kind: Deployment
metadata:
  name: olimpus-deployment
  labels:
    app: olimpus-ilb-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: olimpus-ilb-deployment
  template:
    metadata:
      labels:
        app: olimpus-ilb-deployment
    spec:
      containers:
      - name: olimpus
        image: bramenn/olimpus
        env:
        - name: POSTGRES_URI
          value: "postgresql://bramen:bramen@0.tcp.ngrok.io:19056/olimpus"
        - name: MAX_TICKET_BY_VIEWER
          value: 3
        - name: DEFAUL_FREE_LIMIT_VIWERS
          value: 10
        - name: DEFAUL_FREE_LIMIT_PARTICIPANTS
          value: 5
        ports:
        - containerPort: 80
