apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: olimpus-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: olimpus-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
