apiVersion: v1
kind: Service
metadata:
  name: ilb-svc
spec:
  type: LoadBalancer
  selector:
    app: olimpus-ilb-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
