version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB_FILE: '/run/secrets/postgres_db'
      POSTGRES_USER_FILE: '/run/secrets/postgres_user'
      POSTGRES_PASSWORD_FILE: '/run/secrets/postgres_password'
      POSTGRES_INITDB_ARGS:  '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - ./volumes/schemas:/var/lib/postgresql/data
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    ports:
      - 5432:5432


secrets:
  postgres_db:
    file: ./postgres_db.txt
  postgres_password:
    file: ./postgres_password.txt
  postgres_user:
    file: ./postgres_user.txt
